### ISSUE TITLE
Star size + Read-only mode

### ISSUE THREAD

**Issue by thukuwanjiku** [panietoar/nativescript-vue-star-rating#2]
Appreciation for the good work.
I understand this is a project in progress, however I'm using Nativescript+vue and the size prop isn't working for me, both as a string and number. 

Both 
<StarRating :value="3.5" size="10"
and
<StarRating :value="3.5" : size="10"

give me large stars
![screenshot_20181130-224601-01](https://user-images.githubusercontent.com/17809323/49311465-4a437d00-f4f2-11e8-9c06-06584503a58b.jpeg)

Also please put the readonly mode on the stars

**Comment by panietoar** [comment]
You can put them in readonly by ignoring the event. I'll check the size problem.

**Comment by panietoar** [comment]
I don't see problem with size.

Please play here to see it working:
https://play.nativescript.org/?template=play-vue&id=jDeqtw&v=3

**Comment by thukuwanjiku** [comment]
Your demo works exactly as I want. Perhaps I have some bugs on my local code because it stays the same. I'll try it on a new local project and see. Thanks
